### ISSUE TITLE
How to Install the provided armbian image

### ISSUE THREAD

**Issue by XoBoR** [tomsbasement/twotrees-sk1#1]
Hi,

First of all thank you very much for providing this guide, I managed to update my SK1 to the latest klipper thanks to you.

I wanted to try the Armbian 12 Image you provided, but beeing a Linux noob I don't know what exactly i should do with the provided img file, there doesnt seem to be a boot partition in it?

Would you mind adding a short explanation on how to correctly get that img to the printer?

Thanks again!

**Comment by mechano** [comment]
I think it's not a distribution for noobs of Linux, it needs good knowledge. 

Anyway image writer like Balena Etcher can flash this in the eMMC. 
You have to take from printer, put on the eMMC-to-USB adapter provided with the printer and flash it. 

If the image is bigger than 8GB of the stock eMMC, you can buy an MKS eMMC 32GB for $12 on Aliexpress.

**Comment by bistory** [comment]
Absolutely, I don't want to be pedantic when I say this, but I didn't detail all the steps so as not to have to repair the damage...

**Comment by mechano** [comment]
Put a disclaimer in the first page, that you'll not responsible for every damage occurring from flashing this firmware.

**Comment by bistory** [comment]
> Put a disclaimer in the first page, that you'll not responsible for every damage occurring from flashing this firmware.

Done ! Thanks for the suggestion !
